apiVersion: apps/v1 
kind: Deployment
metadata:
  name: ejercicios
  labels: 
     app: ejercicios

spec:
  replicas: 1 
  selector:
    matchLabels:
      app: ejercicios

  template:
    metadata:
      labels:
        app: ejercicios
    spec:
      containers:
      - name: ejercicios
        image: DOCKER_IMAGE
        imagePullPolicy: Always
        ports:
        - containerPort: 5001
        env:
        - name: AWS_ACCESS_KEY_ID
          value: ENV1
        - name: AWS_SECRET_ACCESS_KEY
          value: ENV2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
