apiVersion: v1
kind: Service
metadata:
  name: ejercicios
  labels:
    app: ejercicios
spec:
  selector:
    app: ejercicios

  ports:
    - port: 5001
      targetPort: 5001

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ejercicios-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: localhost
      http:
        paths:
          - path: /ejercicios
            pathType: Prefix
            backend:
              service:
                name: ejercicios
                port:
                  number: 5001
