apiVersion: v1
kind: Service
metadata:
  name: ejercicios
  labels:
    app: ejercicios
spec:
  selector:
    app: ejercicios

  ports:
    - port: 5001
      targetPort: 5001

  type: LoadBalancer
  loadBalancerIP: "54.161.102.172"

