apiVersion: v1
kind: Service
metadata:
  name: ejercicios
  labels:
    app: ejercicios
spec:
  type: ExternalName
  externalName: a5f58bedf010248db91006bd56c4cec8
  selector:
    app: ejercicios

  ports:
    - port: 5001
      targetPort: 5001

  type: LoadBalancer
