name: Pruebas y Cobertura

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "develop", "main" ]
env:
  ECR_REPOSITORY: ejercicios
  EKS_CLUSTER_NAME: sportapp
  AWS_REGION: us-east-1
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        pytest --cov=src -v -s --cov-fail-under=70
        COVERAGE=$(pytest --cov-report=xml | grep -oP 'total="(.*?)"' | cut -d'"' -f2)
        echo "Coverage is $COVERAGE"
        
    - name: Publish coverage in PR comments
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v5
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const { data } = await github.rest.pulls.createReviewComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.payload.pull_request.number,
            body: `Coverage is ${process.env.COVERAGE}%`
          });
          console.log(data);
